### ISSUE TITLE
Unable to access SMS db (malformed)

### ISSUE THREAD

**Issue by zzph** [MaxiHuHe04/iTunes-Backup-Explorer#17]
Hi,

Awesome work on this project- thank you.

When I try to open `/HomeDomain/Library/SMS/sms.db`, it tells me "database disk image is malformed". 

So I tried:
`sqlite3 sms.db` > `.tables` > ERROR: `database disk image is malformed`

I tried to take a dump to remove any issues- `sqlite3 sms.db ".dump" | sqlite3 new.db` but kept getting `no such table` errors such as
`main.chat_handle_join`.

Any ideas on how to fix this issue?

**Comment by MaxiHuHe04** [comment]
Hi!
It seems like the sms.db file often makes problems. I don't know why. In my backups, they work just fine and I haven't found any other corrupted files yet. That makes it hard to debug. I could imagine that the database wasn't saved in a consistent state before the backup.
Have you tried the `.recover` command instead of `.dump` like recommended in #1? Apparently, `.clone` has also worked for others: https://github.com/mvt-project/mvt/issues/25#issuecomment-883991015.

**Comment by zzph** [comment]
Brilliant- that's the solve, using `.recover`.

So that's:

`sqlite3 sms.db ".recover" | sqlite3 new.db`

Again, thanks so much for the great work on this project

**Comment by MaxiHuHe04** [comment]
I recently discovered something regarding this issue. I don't know if it had really the same cause as it still hasn't happened with the SMS database for me. But I had a few other corrupted database files in a new backup, especially from Safari. It looks like they are not cleanly saved before the backup. I don't know if there were rows missing, but sqlite could at least read them without errors after I disabled the file truncation after decryption. So apparently the file size attribute in the backup database does not get updated correctly sometimes.
Anyway, the program now exports files in two variations if it finds more than a kilobyte of trailing data. Hopefully, this helps in such cases.
