### ISSUE TITLE
"Unable to install java"

### ISSUE THREAD

**Issue by Ka1lIl** [MaxiHuHe04/iTunes-Backup-Explorer#25]
Ive tried restarting my computer, redownloading and deleting java but it does not work and no matter what I do I cannot run the java to run the itunes backup explorer please help me.
![Screenshot 2023-07-12 181135](https://github.com/MaxiHuHe04/iTunes-Backup-Explorer/assets/139397038/0c51ab18-5753-4644-98d2-6a26d5c45a23)

**Comment by MaxiHuHe04** [comment]
@Ka1lIl hey, it seems that you tried to launch the program using the installer of Java instead of with the installed executable of Java.
You have to install it first by double-clicking the Java installer you downloaded. Then, open the command prompt (cmd) and type in `java -jar "C:\Users\YABOI\Downloads\itunes-backup-explorer-1.4.jar"`. If it was installed correctly, you should also be able to just double-click the jar file.
